[tool.poetry]
name = "pystable"
version = "0.1.0"
description = ""
authors = ["mikeyrf <mikeyrf@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
hypothesis = "^6.14.1"
flake8 = "^3.9.2"
pybind11 = {extras = ["global"], version = "^2.6.2"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
